name: pattern_m
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #flutter_polyline_points: ^1.0.0
  flutter_riverpod: ^2.1.3
  geolocator: ^14.0.0
  google_fonts: ^4.0.1
  #google_maps_flutter: ^2.2.3
  intl: ^0.20.2
  isar: ^3.0.5
  isar_flutter_libs:
    path: packages/isar_flutter_libs-3.1.0+1
  google_maps_flutter: ^2.2.3

  logger: ^2.5.0
  path: ^1.8.2
  path_provider: ^2.0.12
  permission_handler: ^12.0.0+1
  riverpod_annotation: ^2.6.1
  location: ^8.0.0
  http: ^0.13.5
  geocoding: ^3.0.0
  #flutter_typeahead: ^4.3.1
  autocomplete_textfield: ^2.0.1
  url_launcher: ^6.1.8
  flutter_polyline_points: ^1.0.0
  google_map_polyline_new: ^0.3.0+2
  #search_map_location: ^0.0.6
  search_map_place_updated: ^0.0.4
  flutter_rating_bar: ^4.0.1
  
dependency_overrides:
  isar_flutter_libs:
    path: packages/isar_flutter_libs-3.1.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
